[package]
name = "hello"
version = "0.1.0"
authors = ["Timothy Pratley <timothypratley@gmail.com>"]
edition = "2018"

[lib]
path = "src/b/type_alias.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
