name: Clojure CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test
    
    - name: Transpile & build examples
      run: |
        pushd examples
        make
        popd

    - name: Transpile & build sql_builder
      run: |
        pushd sql_builder
        make
        popd
